### ISSUE TITLE
astropy version 5.3 bug.

### ISSUE THREAD

**Issue by daniel-muthukrishna** [stevepur/transit-diffImage#2]
astropy version 5.3 causes a bug. Downgrading to astropy==5.1 solves the issue

Issue is caused by astropy==5.3 table division producing masked values instead of NaNs during division.  This causes line 491 of tessDiffImage.py (`dRa[np.isnan(dRa)] = 0`) to produce unexpected behavior, resulting in "no stars on pixels" error.

**Comment by stevepur** [comment]
I am not able to upgrade to astropy==5.3 at this time, so I cannot replicate this bug.  If you fix it please let me know.  I expect that inserting dRa = np.ma.filled(dRa, np.nan) immediately after the divide will allow the code to proceed.  Of course this may happen elsewhere.  Later we'll update our system and do a proper fix.

**Comment by stevepur** [comment]
I checked that adding the line dRa = np.ma.filled(dRa, np.nan) does not break the numpy 5.1 code, so I pushed a version with this line.  Let me know if this did not fix the problem.
